;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((fennel-mode . ((eval . (font-lock-add-keywords 'fennel-mode '(("\\<handler-bind\\>" . 'font-lock-keyword-face))))
                 (eval . (font-lock-add-keywords 'fennel-mode '(("\\<handler-case\\>" . 'font-lock-keyword-face))))
                 (eval . (font-lock-add-keywords 'fennel-mode '(("\\<restart-case\\>" . 'font-lock-keyword-face))))
                 (eval . (font-lock-add-keywords 'fennel-mode '(("\\<define-condition\\>" . 'font-lock-keyword-face))))
                 (eval . (font-lock-add-keywords 'fennel-mode '(("\\<cerror\\>" . 'font-lock-keyword-face))))
                 (eval . (font-lock-add-keywords 'fennel-mode '(("\\<ignore-errors\\>" . 'font-lock-keyword-face))))
                 (eval . (font-lock-add-keywords 'fennel-mode '(("\\<unwind-protect\\>" . 'font-lock-keyword-face))))
                 (eval . (put 'handler-bind 'fennel-indent-function 1))
                 (eval . (put 'handler-case 'fennel-indent-function 1))
                 (eval . (put 'restart-case 'fennel-indent-function 1))
                 (eval . (put 'ignore-errors 'fennel-indent-function 0))
                 (eval . (put 'unwind-protect 'fennel-indent-function 1)))))
